# render.yaml — Superhond Registratie
# Maakt 1 Postgres DB, 1 Node/Express Web Service en 1 Static Site aan.

databases:
  - name: superhond-db
    databaseName: superhond
    user: superhond_user
    plan: free

services:
  # --- API (Node/Express) ---
  - type: web
    name: superhond-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: superhond-db
          property: connectionString
      # Zet deze NA publicatie van de static site op de echte URL
      - key: CORS_ORIGIN
        value: https://superhond-web.onrender.com
      # Optioneel: seed alleen bij 1e deploy
      - key: RUN_SEED
        value: "true"

  # --- Frontend (Static Site) ---
  - type: static_site
    name: superhond-web
    rootDir: public
    buildCommand: ""          # geen build nodig, pure static
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: no-cache
