databases:
  - name: superhond-db
    databaseName: superhond
    user: superhond_user
    plan: free

services:
  - type: web
    name: superhond-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: superhond-db
          property: connectionString
      - key: CORS_ORIGIN
        # update dit na de eerste static deploy naar de echte static site URL
        value: https://superhond-web.onrender.com

  - type: static
    name: superhond-web
    rootDir: public
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: no-cache
