# render.yaml — Superhond Registratie (v0.26.4)
# Maakt 1 Node/Express Web Service (API + config) en 1 Static Site (frontend)

services:
  # --- API (Node/Express) ---
  - type: web
    name: superhond-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/ping
    envVars:
      # === basisomgeving ===
      - key: NODE_ENV
        value: production

      # === GAS koppeling ===
      - key: API_BASE
        value: https://script.google.com/macros/s/AKfycbyxPiFzgCcMplcC5kyFgVPHcIIjDXcQoWdPMEvI2zj-aP6ud8mG49xicSHd8SUcG22sPw/exec

      # === Admin toegang (instellingenpagina) ===
      - key: ADMIN_TOKEN
        value: sh-ADMIN-2025-!Xz3

      # === CORS whitelist (frontend) ===
      - key: CORS_ORIGIN
        value: https://superhond-web.onrender.com

  # --- Frontend (Static Site) ---
  - type: static_site
    name: superhond-web
    rootDir: public
    buildCommand: ""          # geen build nodig
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: no-cache
